(define (deep-map fn s)
  (cond ((null? s) s)
  		((list? (car s)) (cons (deep-map fn (car s)) (deep-map fn (cdr s))))
  		(else (cons (fn (car s)) (deep-map fn (cdr s))))
  		)
)

(define (substitute s old new)
  (cond ((null? s) s)
  		((list? (car s)) (cons (substitute (car s) old new) (substitute (cdr s) old new)))
  		((eq? (car s) old) (cons new (substitute (cdr s) old new)))
  		(else (cons (car s) (substitute (cdr s) old new)))
  	)
)

(define (sub-all s olds news)
    ()
  )


(define (sub-all s olds news)
  	(cond ((null? s) s)
  		  ((list? (car s)) (cons (sub-all (car s) olds news) (sub-all (cdr s) olds news)))
  		  ((contains? olds (car s)) (cons (helper (car s) olds news) (sub-all (cdr s) olds news)))
        (else (cons (car s) (sub-all (cdr s) olds news)))
      )
)

(define (helper v olds news)
  (cond ((eq? v (car olds)) (car news))
    (else (helper v (cdr olds) (cdr news)))
    )
  )

(define (contains? s v)
    (cond ((null? s) #f)
          ((eq? v (car s)) #t)
          (else (contains? (cdr s) v))
          ))